name = "GeoGebra"
uuid = "db4dc2ca-38af-41b7-ab88-76237475b77d"
authors = ["Manabu Higashida <manabu@higashida.net>"]
version = "0.1.2"

[compat]
julia = ">=1.8, <2.0"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
