"""Comm helpers to notify the frontend to inject a GeoGebra applet.

Connects to the frontend comm target `jupyter.ggblab.control` and sends
the kernel-side ingest port or socket path so the frontend can inject
an applet. Exports: `open_comm`, `open_control_comm`, `send_comm`,
`inject_applet`, `get_kernel_id`.
"""


# Prefer a static dependency so precompilation/type-check works
using IJulia

export open_comm, open_control_comm, send_comm, inject_applet, get_kernel_id

"""Open an IJulia Comm to the given `target`.

Arguments:
- `target`: comm target string (e.g. "jupyter.ggblab.control").
- `retries`: number of retries when opening (currently unused).
- `delay`: delay between retries in seconds.

Returns an `IJulia.Comm` instance or throws on error.
"""
function open_comm(target::AbstractString; retries::Integer=1, delay::Real=0.1)
    # Use IJulia's Comm constructor directly; let errors propagate to caller
    return IJulia.Comm(target)
end

"""Open the control comm (`"jupyter.ggblab.control"`).

This is a convenience wrapper around `open_comm`.
"""
open_control_comm() = open_comm("jupyter.ggblab.control")

"""Send a message via an IJulia comm.

Arguments:
- `comm`: the comm object returned by `open_comm`/`open_control_comm`.
- `msg`: a Julia/Python-serializable object to send.

Returns `nothing`.
"""
function send_comm(comm, msg)
    # Call IJulia API directly
    IJulia.send_comm(comm, msg)
    return nothing
end


"""Notify the frontend to inject a GeoGebra applet into the UI.

Keyword arguments:
- `insertMode` : where to insert the applet (default "split-right").
- `appName`    : logical app name passed to frontend (default "suite").
- `useWs`      : when true (default) start a WebSocket ingest server
                 (recommended). When false, a UNIX-domain socket server
                 will be started instead. Note: UNIX-domain sockets are
                 generated by `start_ingest_server()` and returned as
                 the `ingest_path`; when used, the kernel's comm receive
                 handler may be blocked while the kernel status is
                 "busy" (cell executing), so WebSocket mode is generally
                 safer for long-running ingestion.

Returns the payload sent to the frontend (a `Dict{String,Any}`).
"""
function inject_applet(; insertMode::String="split-right", appName::String="suite", useWs::Bool=true)
    comm = open_control_comm()
    if comm === nothing
        throw(ErrorException("Could not open control comm"))
    end
    k = get_kernel_id()
    if k === nothing
        throw(ErrorException("inject_applet: no kernel id available. Ensure code is running inside a Jupyter kernel with IJulia."))
    end
    # Reserve an ingest transport and notify frontend.
    ingest_path = nothing
    ingest_task = nothing
    ingest_port = nothing
    ingest_task_ws = nothing
    try
        function _unpack_server_result(res)
            # Try named tuple access first, then tuple indexing, otherwise return (nothing, nothing)
            try
                return (getproperty(res, :port), getproperty(res, :task))
            catch
                try
                    return (res[1], res[2])
                catch
                    try
                        return (getproperty(res, :path), getproperty(res, :task))
                    catch
                        return (nothing, nothing)
                    end
                end
            end
        end

        if useWs
            res = start_ingest_ws_server()
            pp, tt = _unpack_server_result(res)
            ingest_port = pp
            ingest_task_ws = tt
            @debug "inject_applet: started WebSocket ingest server on port $ingest_port"
        else
            res = start_ingest_server(websocket=false)
            pp, tt = _unpack_server_result(res)
            ingest_path = pp
            ingest_task = tt
            @debug "inject_applet: started socket ingest server on path $ingest_path"
        end
    catch err
        @warn "inject_applet: failed to start ingest server, continuing without ingest socket" err=err
        ingest_path = nothing
    end

    payload = Dict{String,Any}("type"=>"inject", "kernelId"=>k, "insertMode"=>insertMode, "appName"=>appName)
    if ingest_port !== nothing
        payload["wsPort"] = ingest_port
    elseif ingest_path !== nothing
        payload["socketPath"] = ingest_path
    end
    send_comm(comm, payload)
    return payload
end

function get_kernel_id()
    """Return the current Jupyter kernel id extracted from the IJulia
    connection file, or `nothing` if not available.
    """
    # Use IJulia API directly and access known fields to allow type inference
    k = try
        IJulia.get_kernel_or_error()
    catch
        return nothing
    end
    if hasproperty(k, :connection_file)
        cf = k.connection_file
        if isa(cf, String)
            m = match(r"kernel-(.*)\.json", cf)
            if m !== nothing
                return m.captures[1]
            end
        end
    end
    return nothing
end
